### ISSUE TITLE
Render failed due to invalid YAML (1.2.313)

### ISSUE THREAD

**Issue by bcdavasconcelos** [pandoc-ext/multibib#1]
I am getting a `ERROR: Render failed due to invalid YAML` on Quarto 1.2.313.

```
3: bibliography:
4:   sources: test/primary.bib
    ~~~~~~~~~~~~~~~~~~~~~~~~~~
5:   recommended-reading: test/secondary.bib
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
The value must instead be a string.
```

Probably related to https://github.com/quarto-dev/quarto-cli/issues/2349#issuecomment-1240476871.

**Comment by bcdavasconcelos** [comment]
Easy fix is merely to add `validate-yaml: false`.

**Comment by widlarizer** [comment]
Sorry, I don't believe this is resolved at all, and I humbly request reopening the issue, as I think multibib is at fault. Disabling YAML validation on Quarto is a workaround and not a fix. Hunting down incorrect configuration variables of the doc convertor is the exact kind of time wasting activity nobody likes when writing docs, so saving users from that seems valuable. Quarto YAML validation only constrains it to (AFAIK) exactly what Pandoc declares the option is allowed to have in its [official docs for --bibliography](https://pandoc.org/MANUAL.html#option--bibliography). In my view, multibib is objectively incorrect in telling users to put invalid information, and turn off validation. I am going to use the [fork](https://github.com/Mellich/pandoc-multibib/commit/eff6589ff02580234d4a8300387f7b03c9652455) by @Mellich to avoid making Quarto worse for myself due to multibib's incompatibility with Pandoc's actual interface. This fork changes multibib to use `bibliography_` rather than `bibliography`. It actually seems more productive to haul around a fork I sometimes bump than to disable YAML validation. Renaming the field outright would be a breaking change, but I'd guess that some way of supporting either fields (`bibliography` and, say, `multibib`) should work
